### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by DarkSeraphim** [Carleslc/Simple-YAML#1]
Give credit where credit is due. You pretty much copy pasted half the classes (if not more) from [Bukkit](https://github.com/Bukkit/Bukkit/tree/master/src/main/java/org/bukkit/configuration).

Moreover, [their license](https://github.com/Bukkit/Bukkit/blob/master/LICENCE.txt) does not allow you to use it as it currently is used:
- There's no license and no copyright notice of their code
- You need to state what you've changed
- The project would have to be licensed as GPL v3

**Comment by Carleslc** [comment]
You're right, thank you. Firstly I've changed the LICENSE to match GPL v3.

Now what I need to do exactly? Documenting changes from the Bukkit configuration files?

**Comment by DarkSeraphim** [comment]
Documenting changes you made to the files you use from Bukkit I believe.

(Besides it'd probably be nice for the Bukkit team to note that you're using their YAML wrapper as well)

**Comment by Carleslc** [comment]
Ok, I've improved the README and added @author tag to each File.
