### ISSUE TITLE
Is it possible to change the YAML library with a library that has less size?

### ISSUE THREAD

**Issue by portlek** [Carleslc/Simple-YAML#12]
The Simple-YAML project has 350~ kb size. I tested it with another YAML library which has 1.2 YAML 3rd edition support and the file size has been 150~ kb.
![image](https://user-images.githubusercontent.com/12835420/86515710-a6375b80-be23-11ea-8ebe-b6d80032e3d3.png)

**Comment by Carleslc** [comment]
I don't mind to change the library for parsing / dumping YAML as long as the same behaviour can be achieved. I don't know about eo-yaml but I guess it should work. May involve some work, though.

Current usage of SnakeYAML in this library is at YamlConfiguration, YamlConstructor and YamlRepresenter classes.

You can create a pull request with the migration changes if you want to work on it.

**Comment by portlek** [comment]
Yea I know, I did it already but it's not in the simple-yaml fork, I will separate these features to create p.r. for this repo.

**Comment by portlek** [comment]
Also, one more thing that is good with eo-yaml is that it's the fastest and reliable library. I test 4 YAML libraries and the result is this(loading from file)
```
Benchmark                    Mode  Cnt  Score   Error  Units
BenchmarkRunner.eoyaml       avgt    3  0,780 ± 0,089  ms/op
BenchmarkRunner.jacksonyaml  avgt    3  4,874 ± 0,702  ms/op
BenchmarkRunner.snakeyaml    avgt    3  9,532 ± 0,890  ms/op
BenchmarkRunner.yamlbeans    avgt    3  6,773 ± 0,598  ms/op
```
I will try to implement some snakeyaml features into eo-yaml, after that I will open the p.r. again. I hope

**Comment by Carleslc** [comment]
Seems promising!

About the pull request, key ordering and saving dates can be solved with the suggestions I wrote in the review (changing `HashMap` to `LinkedHashMap` when needed and adding `Date.class` to `SCALAR_TYPES`). I don't know if there are better solutions.

Changing indentation for dumping may be an interesting feature to develop in eo-yaml. Avoiding wrapping keys with `-` character would solve some issues with current tests. Strings with `-` character are wrapped too. Strings and keys with `:` character are wrapped too, but that's more understandable.

**Comment by portlek** [comment]
> About the pull request, key ordering and saving dates can be solved with the suggestions I wrote in the review (changing `HashMap` to `LinkedHashMap` when needed and adding `Date.class` to `SCALAR_TYPES`). I don't know if there are better solutions.

the library can set/get dates actually we don't need to add to scalar types. I'm working on eo-yaml library for these features.

**Comment by Carleslc** [comment]
I guess this issue can be closed then, because no other library has significant size + performance benefits at the moment.
