### ISSUE TITLE
Reliable and more powerful unit testing.

### ISSUE THREAD

**Issue by portlek** [Carleslc/Simple-YAML#15]
ATM, the testing is not safe so much. We should add official unit test with jupiter and it should work when we build the project.
```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <version>5.6.2</version>
    <scope>test</scope>
</dependency>
```
Also, need a plugin;
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.2</version>
</plugin>
```
for automatic tests when the project is building.

**Comment by Carleslc** [comment]
You're right. Current tests are not unit tests, they were created for example of usage of the library. However, unit tests with JUnit are preferable for testing.

**Comment by portlek** [comment]
> You're right. Current tests are not unit tests, they were created for example of usage of the library. However, unit tests with JUnit are preferable for testing.

junit = jupiter :D
