### ISSUE TITLE
Is it possible to separate YAML library?

### ISSUE THREAD

**Issue by portlek** [Carleslc/Simple-YAML#16]
Is it possible to separate SnakeYAML into a new module like;
- simple-configuration > includes all common stuffs like;
> utils package
> exceptions package
> configuration package
> configuration/comments
> configuration/file(without yaml classes)
> configuration/serialization

- simple-yaml > includes just snakeyaml dependency and all the yaml classes.
> configuration/file(just YAML classes)

I just want to separate the configuration module and YAML module that's using the configuration module.
I will make a p.r. about that. I hope the point will be more understandable.

**Comment by Carleslc** [comment]
Yes, will be included in Simple-YAML 1.7 (maybe next week), thank you for your proposal.

**Comment by portlek** [comment]
BTW, the dependencies should look like that;
```xml
<dependency>
  <groupId>com.github.Carleslc</groupId>
  <artifactId>Simple-Configuration</artifactId>
  <version>${version}</version>
</dependency>
<dependency>
  <groupId>com.github.Carleslc</groupId>
  <artifactId>Simple-Yaml</artifactId>
  <version>${version}</version>
</dependency>
```

**Comment by Carleslc** [comment]
Reopening until published with next release.
