### ISSUE TITLE
How remove

### ISSUE THREAD

**Issue by TheMajster** [Carleslc/Simple-YAML#2]
Hi, how remove patch from yaml ?

**Comment by Carleslc** [comment]
What do you mean?

You can remove sections or elements setting to null: `yamlFile.set("section.element", null);`
You can delete files with: `yamlFile.deleteFile();`

**Comment by TheMajster** [comment]
if I have comment in config, then yamlFile.set ("section.element", "field"); he removes

**Comment by Carleslc** [comment]
If your file has comments inside you have to save it with `yamlFile.saveWithComments()` instead `yamlFile.save()` to keep comments.
