### ISSUE TITLE
Could it be possible to add more file types?

### ISSUE THREAD

**Issue by portlek** [Carleslc/Simple-YAML#22]
Could it be possible to add more file type modules like;
- Simple-Json
- Simple-Hocon
- Simple-Xml

**Comment by Carleslc** [comment]
I think they could be added building on top of the `Simple-Configuration` module, but I think that's out of the scope of this project to include those file types in this repo (_Simple-YAML_).

**Comment by portlek** [comment]
Alright, I will separate these modules into repository.

**Comment by Carleslc** [comment]
Links to other repositories using the `Simple-Configuration` module can be included in the README so they can be found more easily by those users requiring to use another file type for their configurations.

**Comment by portlek** [comment]
https://github.com/portlek/jsongration
https://github.com/portlek/hocongration
https://github.com/portlek/xmlgration
