### ISSUE TITLE
Nexus maven central is a good alternative to jitpack.

### ISSUE THREAD

**Issue by portlek** [Carleslc/Simple-YAML#29]
I think nexus is a good alternative to the jitpack. 
Also, the dependency should be like that;
```xml
<dependency>
    <groupId>just.domain.name</groupId>
    <artifactId>Simple-Configuration</artifactId>
    <version>1.7</version>
</dependency>
<dependency>
    <groupId>just.domain.name</groupId>
    <artifactId>Simple-Yaml</artifactId>
    <version>1.7</version>
</dependency>
```
`just.domain.name` should be like for example `io.github.portlek` which's not including the `Simple-YAML`. In this case, the groupId should be `me.carleslc` and this will make the library more clear.
But I guess it's not allowed with the jitpack right?

**Comment by Carleslc** [comment]
JitPack is a different repository. It's pretty easy to use. Builds are automatically deployed to JitPack's repository with every commit and release. I think I cannot change the groupId they provide, though.

Publishing to Maven Central would be more trustworthy, that's a fact.

But I would need to host a Nexus instance? I've never used Nexus nor published to Maven Central.

**Comment by portlek** [comment]
Not actually, you can but there is a general sonatype maven central. Here is the tutorial;
https://central.sonatype.org/pages/ossrh-guide.html

**Comment by portlek** [comment]
BTW, 
![image](https://user-images.githubusercontent.com/12835420/88666820-41e97e00-d0e9-11ea-9688-7aaf7e95d367.png)
I can't get the jar 
![image](https://user-images.githubusercontent.com/12835420/88666848-4ada4f80-d0e9-11ea-9408-f5cf7152b255.png)
It can't find it.

**Comment by Carleslc** [comment]
Strange, it is working for me with `com.github.Carleslc.Simple-YAML`.

I was trying to change the groupId of JitPack, and this is also working for me:

```xml
<dependency>
    <groupId>me.carleslc.Simple-YAML</groupId>
    <artifactId>Simple-Configuration</artifactId>
    <version>1.7</version>
</dependency>
```

**Comment by Carleslc** [comment]
I've also attached the javadoc jar to JitPack.

**Comment by Almighty-Satan** [comment]
Any news on this?

**Comment by DxsSucuk** [comment]
> JitPack is a different repository. It's pretty easy to use. Builds are automatically deployed to JitPack's repository with every commit and release. I think I cannot change the groupId they provide, though.

If you own a domain you can change the groupId, better said if you want `me.carleslc` as your groupid you would need to own the domain `carleslc.me`.

Read more [here](https://jitpack.io/docs/#publishing-on-jitpack)!

**Comment by Carleslc** [comment]
> > JitPack is a different repository. It's pretty easy to use. Builds are automatically deployed to JitPack's repository with every commit and release. I think I cannot change the groupId they provide, though.
> 
> If you own a domain you can change the groupId, better said if you want `me.carleslc` as your groupid you would need to own the domain `carleslc.me`.
> 
> Read more [here](https://jitpack.io/docs/#features)!

It's already possible to fetch the dependency using the `me.carleslc` groupId, as stated in the README.

```xml
<dependency>
    <groupId>me.carleslc.Simple-YAML</groupId>
    <artifactId>Simple-Yaml</artifactId>
    <version>1.8.2</version>
</dependency>
```

**Comment by robross0606** [comment]
Agreed, having to set up a separate repository to pull this dependency is a no-go for us due to how we proxy dependency repos.  It is a shame because I would much rather explore using this than directly using `snakeyaml`.  The API looks awesome.
