### ISSUE TITLE
.save() error

### ISSUE THREAD

**Issue by Mario-Greiner** [Carleslc/Simple-YAML#3]
When i call the yamlFile.save(); method i always get this error:

 java.lang.NoClassDefFoundError: com/google/common/io/Files
at org.simpleyaml.configuration.file.FileConfiguration.save(FileConfiguration.java:100)
at org.simpleyaml.configuration.file.YamlFile.save(YamlFile.java:78)

**Comment by Carleslc** [comment]
Thank you for your issue, @Mario-Greiner.

The error says that class Files cannot be found from Google's Guava, which is a dependency of Simple-YAML. Seems that dependencies were not well packed.

I've updated the dependency for Maven in the README, check it out.

In the case you're not using Maven I've uploaded a new JAR that packs the dependencies correctly.

Hope this helps!

**Comment by Mario-Greiner** [comment]
I dont use Maven. Please upload the new JAR
Thanks

**Comment by Carleslc** [comment]
It's already uploaded as I said in the message above.
