### ISSUE TITLE
Add comments programmatically?

### ISSUE THREAD

**Issue by Osiris-Team** [Carleslc/Simple-YAML#34]
Is there a way of doing this with simple-yaml directly?
Like the addDefault() method adds a new value the addComment() method could add comments.

**Comment by Carleslc** [comment]
Sure. [YamlFile](https://carleslc.me/Simple-YAML/doc/Simple-Yaml/org/simpleyaml/configuration/file/YamlFile.html) implements [Commentable](https://carleslc.me/Simple-YAML/doc/Simple-Yaml/org/simpleyaml/configuration/comments/Commentable.html) interface. Each comment is identified by a path (key of key-value pair or section), and there are two kind of comments (`BLOCK`: above a key, `SIDE`: right to a key). Use [`setComment`](https://carleslc.me/Simple-YAML/doc/Simple-Yaml/org/simpleyaml/configuration/file/YamlFile.html#setComment(java.lang.String,java.lang.String,org.simpleyaml.configuration.comments.CommentType)) to add comments and [`getComment`](https://carleslc.me/Simple-YAML/doc/Simple-Yaml/org/simpleyaml/configuration/file/YamlFile.html#getComment(java.lang.String,org.simpleyaml.configuration.comments.CommentType)) to get them.

An example of usage: [YamlCommentsExample](https://github.com/Carleslc/Simple-YAML/blob/master/Simple-Yaml/src/test/java/org/simpleyaml/examples/YamlCommentsExample.java)

**Comment by Osiris-Team** [comment]
@Carleslc Thanks for the quick reply :)
