### ISSUE TITLE
Multilined comments support?

### ISSUE THREAD

**Issue by Osiris-Team** [Carleslc/Simple-YAML#39]

**Comment by Carleslc** [comment]
As specified in [setComment](https://carleslc.me/Simple-YAML/doc/Simple-Yaml/org/simpleyaml/configuration/file/YamlFile.html#setComment(java.lang.String,java.lang.String,org.simpleyaml.configuration.comments.CommentType)) method documentation, multiline comments can be provided using `\n` character.

A comment is identified by a path, so there can only be one comment for each path, this is the reason why the method is called _setComment_ and not _addComment_, but in that comment you can provide multiple lines as you'd do in any String. This is only useful for `BLOCK` comments.

If you need to add a comment with several lines you have two equivalent approaches:

1. Build a single String with several lines using `\n` character and then use `setComment`.

```java
yamlFile.setComment("test", "Line one\nLine two");
```

Or using a `StringBuilder`:

```java
StringBuilder commentBuilder = new StringBuilder();
commentBuilder.append("Line one");
commentBuilder.append('\n');
commentBuilder.append("Line two");
yamlFile.setComment("test", commentBuilder.build());
```

2. Use `setComment` for the first line and then add the following lines prefixing the result of`getComment`.

```java
yamlFile.setComment("test", "Line one");
yamlFile.setComment("test", yamlFile.getComment("test") + '\n' + "Line two");
```

**Comment by Osiris-Team** [comment]
@Carleslc Great thanks
