### ISSUE TITLE
.save() error

### ISSUE THREAD

**Issue by Nejmik242** [Carleslc/Simple-YAML#40]
Error: https://hastebin.com/tiyecimuku.css
Code: 
TestConfig.java: https://hastebin.com/rimijikuja.java
CustomConfiguration: https://hastebin.com/uzukuqiqer.kotlin

**Comment by portlek** [comment]
probably it because the bukkit's snakeyaml version is outdated.

**Comment by Nejmik242** [comment]
> 
> 
> probably it because the bukkit's snakeyaml version is outdated.

How to fix it?

**Comment by portlek** [comment]
use maven shade plugin with relocation.

**Comment by Nejmik242** [comment]
I copied the files from the new snakeyaml to the paperspigot engine and it works. Thank you for your help.
