### ISSUE TITLE
How can I use defaults?

### ISSUE THREAD

**Issue by byNoobiYT** [Carleslc/Simple-YAML#5]
Hi,
I added some keys and values to the default map, but they have not been added to this file. So how can I use them for pre-set my yml file? 
Sorry for my bad English :)

**Comment by Carleslc** [comment]
Default values are only stored in memory if `options().copyDefaults()` is set to false. This option is set to false by default, but is set to true on the first `load()`.

You can enable copying the default options with
```
yamlFile.options().copyDefaults(true);
```

Another option is to use `yamlFile.load()` after creating the file with `yamlFile.createNewFile(true)` the first time. I've updated the _YamlTest.java_ file using this behavior.

**Comment by byNoobiYT** [comment]
Thank you!
