### ISSUE TITLE
Comments being inserted twice

### ISSUE THREAD

**Issue by Mezy** [Carleslc/Simple-YAML#6]
Original file:
![original](https://user-images.githubusercontent.com/22718012/71584119-91df7280-2b11-11ea-8993-30c8d7012f7f.png)
After saving it with comments:
![with-comments](https://user-images.githubusercontent.com/22718012/71584126-999f1700-2b11-11ea-9628-575c29a3636c.png)
The comments are inserted twice, this also means the commentsWritten value is increased twice meaning the last comment of the file won't be saved as "commentsWritten < n" is false. I solved this issue by removing the comment from the comments list after it's inserted once but this won't work for everyone.

**Comment by Carleslc** [comment]
This is happening up to v1.4 due to ambiguity for keys with the same name (cannot differentiate if the comment is referring to sub-section-1.list or sub-section-2.list). I've updated the way this API was handling comments so from v1.5 this issue is fixed.
